const PERMISSIONS = {
  CAN_CREATE_THREAD: "CAN_CREATE_THREAD",
  CAN_DO_QUIZ: "CAN_DO_QUIZ",
  CAN_FILTER_AND_SORT_QUIZZES: "CAN_FILTER_AND_SORT_QUIZZES",
  CAN_GIVE_RATING: "CAN_GIVE_RATING",
  CAN_MAKE_FAVORITE_QUIZ: "CAN_MAKE_FAVORITE_QUIZ",
  CAN_MANAGE_POST: "CAN_MANAGE_POST",
  CAN_MANAGE_QUIZ: "CAN_MANAGE_QUIZ",
  CAN_MANAGE_THREAD: "CAN_MANAGE_THREAD",
  CAN_REPLY_IN_THREAD: "CAN_REPLY_IN_THREAD",
  CAN_VIEW_BOARD_STATISTICS: "CAN_VIEW_BOARD_STATISTICS",
  CAN_VIEW_USER_STATISTICS: "CAN_VIEW_USER_STATISTICS",
};

module.exports = PERMISSIONS;
